# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w9qWylwB5WdKEWulXMH3HuZ_kTsPxfgE
"""

import streamlit as st
import pickle
import pandas as pd
import requests
st.title("Movie Recommendation System")

movies=pickle.load(open("/Users/sushmajain/Desktop/Movie_recom_system/movie_list.pkl",'rb'))
sim=pickle.load(open("/Users/sushmajain/Desktop/Movie_recom_system/similarity.pkl",'rb'))

movie_list=movies['title'].values
option=st.selectbox('Choose your movie',movie_list)

def poster(movie_id):
  response=requests.get("https://api.themoviedb.org/3/movie/{}?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US".format(movie_id))
  data=response.json()
  path=data['poster_path']
  full_path="https://image.tmdb.org/t/p/w500/" + path

def recommend(movie):
   index=movies[movies['title']==movie].index[0]
   mv_list=sorted(list(enumerate(sim[index])),reverse=True,key=lambda x:x[1])[1:6] #taking first 5 movies sorted on the basis of index
   recom_movies=[]
   recom_poster=[]
   for i in mv_list :
      movie_id=movies.iloc[i[0]].movie_id #we need to fetch movie poster
      recom_movies.append(movies.iloc[i[0]].title)
      recom_poster.append(poster(movie_id))
   return recom_movies,recom_poster

if st.button('Recommend'):
  name,poster=recommend(option)
  col1,col2,col3,col4,col5=st.columns(5)
  with col1:
        st.text(name[0])
        #st.image(poster[0])
  with col2:
        st.text(name[1])
        #st.image(poster[1])
  with col3:
        st.text(name[2])
        #st.image(poster[2])
  with col4:
        st.text(name[3])
        #st.image(poster[3])
  with col5:
        st.text(name[4])
        #st.image(poster[4])

